let lastIndex = -1;
const quotes = [
"Trust Krishna's timing.",
"Every soul is eternal.",
"Let your heart rest in Krishna.",
"Faith is stronger than fear.",
"Krishna is always with you.",
"Love without expecting anything.",
"Peace begins with devotion.",
"Your karma shapes your future.",
"Smile, Krishna has a plan.",
"Choose kindness every day.",
"Devotion is the greatest strength.",
"Everything happens for your highest good.",
"Stay calm and trust Krishna.",
"The soul never dies.",
"Forgive and move forward.",
"Krishna is the light within you.",
"Let go of what you can't control.",
"Gratitude attracts blessings.",
"Every sunrise is Krishna's gift.",
"Faith turns darkness into light.",
"Be patient. Miracles take time.",
"Love is the highest devotion.",
"Keep chanting Hare Krishna.",
"Every challenge teaches something.",
"Krishna never leaves a pure heart.",
"Choose peace over anger.",
"Believe in divine timing.",
"Stay humble, stay blessed.",
"Your heart knows the way.",
"Joy grows through devotion.",
"The mind finds peace in Krishna.",
"Your soul belongs to the Divine.",
"Prayer changes everything.",
"Hope blooms through faith.",
"Krishna's love never fades.",
"Serve with compassion.",
"Silence strengthens the spirit.",
"Walk the path of dharma.",
"Every breath is a blessing.",
"Love is Krishna's language.",
"Trust the unseen path.",
"Kindness is true devotion.",
"Patience brings divine rewards.",
"The heart remembers Krishna.",
"Seek wisdom over worry.",
"Stay rooted in faith.",
"Light shines within you.",
"Grace follows surrender.",
"Choose faith every morning.",
"Krishna guides every sincere heart.",
  "Where there is Krishna, there is hope.",
"A peaceful mind is true wealth.",
"Let faith replace fear.",
"Krishna sees every good deed.",
"Love is the purest offering.",
"The soul is beyond birth and death.",
"Every prayer is heard.",
"Be fearless in righteousness.",
"Your journey has divine purpose.",
"Trust the process of life.",
"Krishna never abandons the faithful.",
"Choose compassion over pride.",
"Serve with a joyful heart.",
"Wisdom begins with humility.",
"The Divine lives within you.",
"Peace comes from surrender.",
"Keep your heart pure.",
"Every ending is a new beginning.",
"Faith lights the darkest path.",
"Walk with courage and devotion.",
"Krishna's grace knows no limits.",
"Patience is spiritual strength.",
"Detach from worry.",
"Let your actions inspire others.",
"Truth always shines.",
"Hope blooms through devotion.",
"Every challenge hides a blessing.",
"Live with gratitude.",
"Choose goodness every day.",
"The heart finds home in Krishna.",
"Your destiny unfolds perfectly.",
"Trust divine wisdom.",
"Keep smiling through faith.",
"Every soul deserves kindness.",
"Prayer brings inner peace.",
"Joy grows where faith lives.",
"Krishna's love is endless.",
"Believe in miracles.",
"Every sunrise is a fresh blessing.",
"Forgiveness frees the heart.",
"Dharma leads to peace.",
"Stay gentle and strong.",
"Kind words are sacred.",
"The Divine is always near.",
"Faith transforms fear into courage.",
"Love is never wasted.",
"Your soul is limitless.",
"Grace follows gratitude.",
"Trust with all your heart.",
"Krishna is your eternal friend."
"Krishna's smile removes every fear.",
"The strongest heart is filled with devotion.",
"Walk in faith, not in doubt.",
"Your soul shines brighter than the sun.",
"Every moment with Krishna is a blessing.",
"Love without conditions.",
"The path of truth never fails.",
"Keep Krishna in every heartbeat.",
"Faith makes the impossible possible.",
"Peace begins within.",
"Offer your worries to Krishna.",
"The Divine never forgets you.",
"Be calm in every storm.",
"True victory is over your own mind.",
"Krishna's wisdom is timeless.",
"Stay humble, stay blessed.",
"Devotion is life's greatest treasure.",
"Every prayer reaches Krishna.",
"The heart that loves Krishna never feels alone.",
"Be grateful for today.",
"Trust the journey Krishna has written.",
"Kindness is the language of the soul.",
"Let your faith be stronger than your fears.",
"Krishna's blessings arrive at the perfect time.",
"Your purpose is greater than your problems.",
"Choose forgiveness over anger.",
"Every act of love is worship.",
"Walk gently and speak kindly.",
"The soul blooms through devotion.",
"Hope is Krishna's gift.",
"The light of Krishna never fades.",
"Keep your thoughts pure.",
"Patience is also a prayer.",
"Krishna protects those who trust Him.",
"Live simply, love deeply.",
"Every sunrise is another chance to grow.",
"Find strength in surrender.",
"The Divine path is always worth following.",
"Stay faithful through every season.",
"Love is the highest form of devotion.",
"Every breath is Krishna's blessing.",
"The peaceful heart hears Krishna clearly.",
"Never lose hope in difficult times.",
"Faith brings clarity.",
"Choose joy every single day.",
"Krishna walks beside you always.",
"The greatest wealth is inner peace.",
"Let gratitude fill your heart.",
"Believe that better days are coming.",
"Your soul belongs to eternity."
"Krishna reminds me that I am never alone.",
"I trust the process of life.",
"I choose patience over haste.",
"My soul is nourished by devotion.",
"Every prayer reaches Krishna.",
"I live with honesty and integrity.",
"Krishna fills my life with meaning.",
"I choose faith in uncertain times.",
"My heart is open to miracles.",
"I walk with confidence and grace.",
"Krishna teaches me to stay present.",
"I release all unnecessary burdens.",
"I celebrate the goodness around me.",
"My spirit remains peaceful.",
"Krishna blesses my family with love.",
"I choose wisdom before reacting.",
"Every day is an opportunity to grow.",
"My kindness creates positive change.",
"Krishna strengthens my character.",
"I welcome divine abundance.",
"My heart rests in gratitude.",
"I choose truth in every situation.",
"Krishna teaches me resilience.",
"I shine with inner light.",
"Every experience helps me evolve.",
"I find joy in simple moments.",
"Krishna's love gives me courage.",
"I welcome new beginnings.",
"My heart overflows with hope.",
"I trust Krishna's loving guidance.",
"I spread peace wherever I go.",
"I grow stronger through faith.",
"Krishna helps me forgive myself.",
"I embrace every blessing with gratitude.",
"My soul radiates positivity.",
"I choose compassion every day.",
"Krishna fills my heart with contentment.",
"I let peace replace worry.",
"Every step I take is meaningful.",
"My faith brings me clarity.",
"Krishna inspires my highest potential.",
"I honor myself with kindness.",
"I trust that love always wins.",
"My heart is filled with divine joy.",
"Krishna helps me see the good in others.",
"I remain hopeful through every season.",
"I welcome happiness into my life.",
"Every day is a gift from Krishna.",
"I choose gratitude again and again.",
"My soul walks in Krishna's light.",
];

function newQuote() {
    let random;

    do {
        random = Math.floor(Math.random() * quotes.length);
    } while (random === lastIndex);

    lastIndex = random;

    document.getElementById("quote").innerText = quotes[random];
}

window.onload = newQuote;
